// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_TestVine_RCPPEXPORTS_H_GEN_
#define RCPP_TestVine_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace TestVine {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("TestVine", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("TestVine", "_TestVine_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in TestVine");
            }
        }
    }

    inline double Hfunc2_call() {
        typedef SEXP(*Ptr_Hfunc2_call)();
        static Ptr_Hfunc2_call p_Hfunc2_call = NULL;
        if (p_Hfunc2_call == NULL) {
            validateSignature("double(*Hfunc2_call)()");
            p_Hfunc2_call = (Ptr_Hfunc2_call)R_GetCCallable("TestVine", "_TestVine_Hfunc2_call");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Hfunc2_call();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

}

#endif // RCPP_TestVine_RCPPEXPORTS_H_GEN_
