// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/TestVine.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// Hfunc2_call
double Hfunc2_call();
static SEXP _TestVine_Hfunc2_call_try() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(Hfunc2_call());
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _TestVine_Hfunc2_call() {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_TestVine_Hfunc2_call_try());
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _TestVine_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("double(*Hfunc2_call)()");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _TestVine_RcppExport_registerCCallable() { 
    R_RegisterCCallable("TestVine", "_TestVine_Hfunc2_call", (DL_FUNC)_TestVine_Hfunc2_call_try);
    R_RegisterCCallable("TestVine", "_TestVine_RcppExport_validate", (DL_FUNC)_TestVine_RcppExport_validate);
    return R_NilValue;
}
