# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gaussian_hfunc <- function() {
    invisible(.Call('_TestVine_Gaussian_hfunc', PACKAGE = 'TestVine'))
}

Student_hfunc <- function() {
    invisible(.Call('_TestVine_Student_hfunc', PACKAGE = 'TestVine'))
}

Clayton_hfunc <- function() {
    invisible(.Call('_TestVine_Clayton_hfunc', PACKAGE = 'TestVine'))
}

Gumbel_hfunc <- function() {
    invisible(.Call('_TestVine_Gumbel_hfunc', PACKAGE = 'TestVine'))
}

Frank_hfunc <- function() {
    invisible(.Call('_TestVine_Frank_hfunc', PACKAGE = 'TestVine'))
}

Joe_hfunc <- function() {
    invisible(.Call('_TestVine_Joe_hfunc', PACKAGE = 'TestVine'))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_TestVine_RcppExport_registerCCallable', PACKAGE = 'TestVine')
})
