# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_TestVine_timesTwo', PACKAGE = 'TestVine', x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_TestVine_RcppExport_registerCCallable', PACKAGE = 'TestVine')
})
