# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Hfunc2_call <- function() {
    .Call('_TestVine_Hfunc2_call', PACKAGE = 'TestVine')
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_TestVine_RcppExport_registerCCallable', PACKAGE = 'TestVine')
})
